In [1]:
import sys
print(sys.executable)

d:\Infosys\AI-Skin-Intelligence-Personalized-Skincare-Planner\backend\venv\Scripts\python.exe

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [4]:
products = pd.read_csv("../dataset/product_info.csv")

In [5]:
products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,variation_desc,ingredients,price_usd,value_price_usd,sale_price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,NaN,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...",35.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,NaN,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,NaN,NaN,0,0,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [6]:
products.shape

(8494, 27)

In [7]:
products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='str')

In [8]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   str
 1   product_name        8494 non-null   str
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   str
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   str
 8   variation_type      7050 non-null   str
 9   variation_value     6896 non-null   str
 10  variation_desc      1250 non-null   str
 11  ingredients         7549 non-null   str
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   str
 21  primary_category    8494 non-null   str
 22  secondary_category  8486 non-null   str
 23  tertiary_category   7504 non-null   str
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), str(12)
memory usage: 1.7 MB

In [9]:
products.isnull().sum().sort_values(ascending=False)

sale_price_usd        8224
value_price_usd       8043
variation_desc        7244
child_max_price       5740
child_min_price       5740
highlights            2207
size                  1631
variation_value       1598
variation_type        1444
tertiary_category      990
ingredients            945
rating                 278
reviews                278
secondary_category       8
loves_count              0
product_id               0
brand_name               0
product_name             0
brand_id                 0
out_of_stock             0
online_only              0
new                      0
limited_edition          0
price_usd                0
sephora_exclusive        0
primary_category         0
child_count              0
dtype: int64

In [10]:
products.describe()

,brand_id,loves_count,rating,reviews,price_usd,value_price_usd,sale_price_usd,limited_edition,new,online_only,out_of_stock,sephora_exclusive,child_count,child_max_price,child_min_price
count,8494.000000,8.494000e+03,8216.000000,8216.000000,8494.000000,451.000000,270.000000,8494.000000,8494.000000,8494.000000,8494.000000,8494.000000,8494.000000,2754.000000,2754.000000
mean,5422.440546,2.917957e+04,4.194513,448.545521,51.655595,91.168537,20.207889,0.070285,0.071698,0.219096,0.073699,0.279374,1.631622,53.792023,39.665802
std,1709.595957,6.609212e+04,0.516694,1101.982529,53.669234,79.195631,24.327352,0.255642,0.258002,0.413658,0.261296,0.448718,5.379470,58.765894,38.685720
min,1063.000000,0.000000e+00,1.000000,1.000000,3.000000,0.000000,1.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000
25%,5333.000000,3.758000e+03,3.981725,26.000000,25.000000,45.000000,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22.000000,19.000000
50%,6157.500000,9.880000e+03,4.289350,122.000000,35.000000,67.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,32.000000,28.000000
75%,6328.000000,2.684125e+04,4.530525,418.000000,58.000000,108.500000,25.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,59.000000,42.000000
max,8020.000000,1.401068e+06,5.000000,21281.000000,1900.000000,617.000000,320.000000,1.000000,1.000000,1.000000,1.000000,1.000000,105.000000,570.000000,400.000000

In [11]:
products["primary_category"].value_counts()

primary_category
Skincare           2420
Makeup             2369
Hair               1464
Fragrance          1432
Bath & Body         405
Mini Size           288
Men                  60
Tools & Brushes      52
Gifts                 4
Name: count, dtype: int64

In [12]:
products["secondary_category"].value_counts().head(20)

secondary_category
Women                        875
Hair Styling & Treatments    757
Eye                          711
Face                         659
Moisturizers                 551
Value & Gift Sets            498
Treatments                   466
Shampoo & Conditioner        431
Lip                          411
Cleansers                    361
Candles & Home Scents        263
Brushes & Applicators        246
Body Moisturizers            220
Mini Size                    187
Eye Care                     186
Masks                        166
Cheek                        165
Tools                        153
Makeup                       137
Men                          135
Name: count, dtype: int64

In [13]:
products["rating"].describe()

count    8216.000000
mean        4.194513
std         0.516694
min         1.000000
25%         3.981725
50%         4.289350
75%         4.530525
max         5.000000
Name: rating, dtype: float64

In [14]:
products[["product_name", "primary_category", "rating", "price_usd"]].head(10)

,product_name,primary_category,rating,price_usd
0,Fragrance Discovery Set,Fragrance,3.6364,35.0
1,La Habana Eau de Parfum,Fragrance,4.1538,195.0
2,Rainbow Bar Eau de Parfum,Fragrance,4.2500,195.0
3,Kasbah Eau de Parfum,Fragrance,4.4762,195.0
4,Purple Haze Eau de Parfum,Fragrance,3.2308,195.0
5,Kasbah Eau de Parfum Travel Spray,Fragrance,4.4762,30.0
6,Purple Haze Eau de Parfum Travel Spray,Fragrance,3.2308,30.0
7,Invisible Post Eau de Parfum,Fragrance,3.6250,195.0
8,Capri Eau de Parfum,Fragrance,3.5714,195.0
9,Invisible Post Eau de Parfum Travel Spray,Fragrance,3.6250,30.0

In [15]:
cleaned_products = products[
    [
        "product_id",
        "product_name",
        "brand_name",
        "ingredients",
        "price_usd",
        "rating",
        "reviews",
        "loves_count",
        "highlights",
        "primary_category",
        "secondary_category",
        "tertiary_category"
    ]
]

cleaned_products.head()

,product_id,product_name,brand_name,ingredients,price_usd,rating,reviews,loves_count,highlights,primary_category,secondary_category,tertiary_category
0,P473671,Fragrance Discovery Set,19-69,"['Capri Eau de Parfum:', 'Alcohol Denat. (SD A...",35.0,3.6364,11.0,6320,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets
1,P473668,La Habana Eau de Parfum,19-69,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,4.1538,13.0,3827,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume
2,P473662,Rainbow Bar Eau de Parfum,19-69,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,4.2500,16.0,3253,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume
3,P473660,Kasbah Eau de Parfum,19-69,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,4.4762,21.0,3018,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume
4,P473658,Purple Haze Eau de Parfum,19-69,"['Alcohol Denat. (SD Alcohol 39C), Parfum (Fra...",195.0,3.2308,13.0,2691,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume

In [16]:
cleaned_products.isnull().sum()

product_id               0
product_name             0
brand_name               0
ingredients            945
price_usd                0
rating                 278
reviews                278
loves_count              0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
dtype: int64

In [17]:
cleaned_products["primary_category"].value_counts()

primary_category
Skincare           2420
Makeup             2369
Hair               1464
Fragrance          1432
Bath & Body         405
Mini Size           288
Men                  60
Tools & Brushes      52
Gifts                 4
Name: count, dtype: int64

In [18]:
skincare_products = cleaned_products[
    cleaned_products["primary_category"] == "Skincare"
].copy()

skincare_products.shape

(2420, 12)

In [19]:
skincare_products.isnull().sum()

product_id              0
product_name            0
brand_name              0
ingredients           134
price_usd               0
rating                 69
reviews                69
loves_count             0
highlights            417
primary_category        0
secondary_category      0
tertiary_category     380
dtype: int64

In [20]:
skincare_products.head(10)

,product_id,product_name,brand_name,ingredients,price_usd,rating,reviews,loves_count,highlights,primary_category,secondary_category,tertiary_category
89,P439055,GENIUS Sleeping Collagen Moisturizer,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,4.5413,1321.0,33910,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Moisturizers,Moisturizers
90,P421277,GENIUS Liquid Collagen Serum,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,4.0259,1159.0,67870,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Treatments,Face Serums
91,P467602,Triple Algae Eye Renewal Balm Eye Cream,Algenist,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",68.0,4.5306,1142.0,17890,NaN,Skincare,Eye Care,Eye Creams & Treatments
92,P432045,GENIUS Liquid Collagen Lip Treatment,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",29.0,3.8721,649.0,44448,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Skincare,Lip Balms & Treatments,NaN
93,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,Algenist,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",28.0,4.4134,508.0,27278,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Skincare,Sunscreen,Face Sunscreen
94,P384537,GENIUS Ultimate Anti-Aging Cream,Algenist,"['Water (Aqua, Eau), Caprylic/Capric Triglycer...",112.0,4.2525,503.0,19733,"['Vegan', 'Collagen', 'Hypoallergenic', 'Good ...",Skincare,Moisturizers,Moisturizers
95,P388200,GENIUS Ultimate Anti-Aging Melting Cleanser,Algenist,"['C12-15 Alkyl Benzoate, Ethylhexyl Palmitate,...",38.0,4.0569,334.0,9314,NaN,Skincare,Cleansers,Face Wash & Cleansers
96,P296413,Gentle Rejuvenating Cleanser,Algenist,"['Water, Sodium Cocoyl Isethionate, Glyceryl S...",28.0,4.2689,264.0,7681,NaN,Skincare,Cleansers,Face Wash & Cleansers
97,P500716,10 Day Results Kit,Algenist,"['GENIUS Liquid Collagen:', 'Collagen (Vegan),...",88.0,4.8023,258.0,3206,"['Vegan', 'Good for: Loss of firmness', 'Good ...",Skincare,Value & Gift Sets,NaN
98,P379907,Advanced Anti-Aging Repairing Oil,Algenist,"['Chlorella Protothecoides Oil, Cetearyl Ethyl...",82.0,4.4531,245.0,10676,NaN,Skincare,Moisturizers,Face Oils

In [21]:
skincare_products["ingredients"] = skincare_products["ingredients"].fillna("Unknown")

skincare_products["highlights"] = skincare_products["highlights"].fillna("Not Available")

skincare_products["tertiary_category"] = skincare_products["tertiary_category"].fillna("Unknown")

skincare_products["rating"] = skincare_products["rating"].fillna(
    skincare_products["rating"].median()
)

skincare_products["reviews"] = skincare_products["reviews"].fillna(0)

In [22]:
skincare_products.isnull().sum()

product_id            0
product_name          0
brand_name            0
ingredients           0
price_usd             0
rating                0
reviews               0
loves_count           0
highlights            0
primary_category      0
secondary_category    0
tertiary_category     0
dtype: int64

In [23]:
skincare_products.to_csv("../dataset/cleaned_skincare_products.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [1]:
import pandas as pd

df = pd.read_csv("../dataset/cleaned_skincare_products.csv")

df.head()

,product_id,product_name,brand_name,ingredients,price_usd,rating,reviews,loves_count,highlights,primary_category,secondary_category,tertiary_category
0,P439055,GENIUS Sleeping Collagen Moisturizer,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Ethylh...",98.0,4.5413,1321.0,33910,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Moisturizers,Moisturizers
1,P421277,GENIUS Liquid Collagen Serum,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Propan...",115.0,4.0259,1159.0,67870,"['Vegan', 'Good for: Loss of firmness', 'Colla...",Skincare,Treatments,Face Serums
2,P467602,Triple Algae Eye Renewal Balm Eye Cream,Algenist,"['Aqua (Water/Eau), Stearic Acid, Isopropyl Is...",68.0,4.5306,1142.0,17890,Not Available,Skincare,Eye Care,Eye Creams & Treatments
3,P432045,GENIUS Liquid Collagen Lip Treatment,Algenist,"['Collagen (Vegan)*, Water (Aqua, Eau), Glycer...",29.0,3.8721,649.0,44448,"['Vegan', 'Good for: Loss of firmness', 'Plump...",Skincare,Lip Balms & Treatments,Unknown
4,P311143,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,Algenist,"['Octinoxate 7.5%, Titanium Dioxide 2%, Zinc O...",28.0,4.4134,508.0,27278,"['Vegan', 'Hypoallergenic', 'UV Protection', '...",Skincare,Sunscreen,Face Sunscreen

In [2]:
df.columns

Index(['product_id', 'product_name', 'brand_name', 'ingredients', 'price_usd',
       'rating', 'reviews', 'loves_count', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category'],
      dtype='str')

In [3]:
# Create one text column containing important product information

df["combined_features"] = (
    df["product_name"].astype(str) + " " +
    df["brand_name"].astype(str) + " " +
    df["primary_category"].astype(str) + " " +
    df["secondary_category"].astype(str) + " " +
    df["tertiary_category"].astype(str) + " " +
    df["highlights"].astype(str) + " " +
    df["ingredients"].astype(str)
)

df[["product_name", "combined_features"]].head()

,product_name,combined_features
0,GENIUS Sleeping Collagen Moisturizer,GENIUS Sleeping Collagen Moisturizer Algenist ...
1,GENIUS Liquid Collagen Serum,GENIUS Liquid Collagen Serum Algenist Skincare...
2,Triple Algae Eye Renewal Balm Eye Cream,Triple Algae Eye Renewal Balm Eye Cream Algeni...
3,GENIUS Liquid Collagen Lip Treatment,GENIUS Liquid Collagen Lip Treatment Algenist ...
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,SUBLIME DEFENSE Ultra Lightweight UV Defense F...

In [4]:
df[["product_name", "combined_features"]].head()

,product_name,combined_features
0,GENIUS Sleeping Collagen Moisturizer,GENIUS Sleeping Collagen Moisturizer Algenist ...
1,GENIUS Liquid Collagen Serum,GENIUS Liquid Collagen Serum Algenist Skincare...
2,Triple Algae Eye Renewal Balm Eye Cream,Triple Algae Eye Renewal Balm Eye Cream Algeni...
3,GENIUS Liquid Collagen Lip Treatment,GENIUS Liquid Collagen Lip Treatment Algenist ...
4,SUBLIME DEFENSE Ultra Lightweight UV Defense F...,SUBLIME DEFENSE Ultra Lightweight UV Defense F...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer
tfidf = TfidfVectorizer(stop_words="english")

# Convert text into numerical vectors
tfidf_matrix = tfidf.fit_transform(df["combined_features"])

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (2420, 5944)